-- MySQL Script generated by MySQL Workbench
-- Mon May  6 20:34:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema motherpakar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema motherpakar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `motherpakar` DEFAULT CHARACTER SET utf8 ;
USE `motherpakar` ;

-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_kerusakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_kerusakan` (
  `kd_kerusakan` CHAR(3) NOT NULL,
  `kerusakan` TEXT(1000) NOT NULL,
  PRIMARY KEY (`kd_kerusakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_penyebab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_penyebab` (
  `kd_penyebab` CHAR(3) NOT NULL,
  `penyebab` TEXT(1000) NOT NULL,
  PRIMARY KEY (`kd_penyebab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_gejala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_gejala` (
  `kd_gejala` CHAR(3) NOT NULL,
  `gejala` TEXT(1000) NOT NULL,
  PRIMARY KEY (`kd_gejala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_solusi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_solusi` (
  `kd_solusi` CHAR(3) NOT NULL,
  `solusi` TEXT(1000) NULL,
  PRIMARY KEY (`kd_solusi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_relasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_relasi` (
  `kd_kerusakan` CHAR(3) NOT NULL,
  `kd_gejala` VARCHAR(100) NOT NULL,
  `kd_solusi` VARCHAR(100) NOT NULL,
  `kd_penyebab` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`kd_kerusakan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `jenis` ENUM('pengguna', 'pakar') NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_kosultasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_kosultasi` (
  `id_konsultasi` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `waktu` DATETIME NOT NULL,
  `kd_kerusakan` CHAR(3) NOT NULL,
  PRIMARY KEY (`id_konsultasi`),
  CONSTRAINT `user`
    FOREIGN KEY (`id_user`)
    REFERENCES `motherpakar`.`tbl_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `motherpakar`.`tbl_konsultasi_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motherpakar`.`tbl_konsultasi_detail` (
  `id_konsultasi` INT NOT NULL,
  `kd_gejala` CHAR(3) NOT NULL,
  `jawab` CHAR(1) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
